name = "galvatron-api"
main = "src/index.ts"
compatibility_date = "2024-08-06"

[build]
command = "pnpm run build"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "API_KEYS"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"